-libraryjars C:\WTK22\lib\midpapi20.jar;C:\WTK22\lib\wma11.jar;C:\WTK22\lib\cldcapi10.jar
-injars C:\WTK22\apps\Line5\bin\Line5.jar
-outjar C:\DOCUME~1\Carlo\IMPOST~1\Temp\Line5.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
