-libraryjars C:\WTK22\lib\midpapi20.jar;C:\WTK22\lib\wma11.jar;C:\WTK22\lib\cldcapi10.jar
-injars C:\WTK22\apps\CiapaTalpa\bin\CiapaTalpa.jar
-outjar C:\DOCUME~1\Carlo\IMPOST~1\Temp\CiapaTalpa.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
