-libraryjars C:\WTK22\lib\midpapi20.jar;C:\WTK22\lib\cldcapi10.jar
-injars C:\WTK22\apps\PallaNuoto\bin\PallaNuoto.jar
-outjar C:\DOCUME~1\Carlo\IMPOST~1\Temp\PallaNuoto.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
