-libraryjars C:\WTK22\lib\midpapi20.jar;C:\WTK22\lib\cldcapi10.jar
-injars C:\WTK22\apps\ForzaP4\bin\ForzaP4.jar
-outjar C:\DOCUME~1\Carlo\IMPOST~1\Temp\ForzaP4.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
